windowrule {
  name = suppress-max
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = media-players
  match:class = ^(mpv|imv)$
  fullscreen = on
}

windowrule {
  name = matplotlib-float
  match:class = ^(Matplotlib)$
  float = on
}

windowrule {
  name = copyq-settings
  match:class = ^(com.github.hluk.copyq)$
  float = on
  size = 500 500
  move = 1420 578
}

windowrule {
  name = dolphin-settings
  match:class = ^(org.kde.dolphin)$
  float = on
  size = 1400 800
}

windowrule {
  name = xdg-portal
  match:class = ^(xdg-desktop-portal-gtk)$
  float = on
}

windowrule {
  name = choose-files-title
  match:title = ^(Choose Files)$
  float = on
}

windowrule {
  name = choose-login-firefox
  match:title = ^(Login | Figma — Mozilla Firefox)$
  float = on
  center = on
}

windowrule {
  name = blender-file-view
  match:class = ^(blender)$
  match:title = ^(Blender File View)
  size = 1400 800
}

windowrule {
  name = special-firefox
  match:title = ^.*(Mozilla Firefox).*$
  match:class = ^(firefox)$
  workspace = 5
}

windowrule {
  name = telegraph
  match:title = ^.*(Telegraph)$
  float = on
}

layerrule {
  name = screenshot-fade
  match:namespace = ^selection$
  animation = fade
}

